create table workout_sets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user text not null,
  exercise text not null,
  warmup text not null,
  weight text not null,
  reps text not null,
  goal text not null
);

-- Enable Row Level Security (RLS)
alter table workout_sets enable row level security;

-- Create a policy that allows all operations (since we're not using auth)
create policy "Allow all operations for everyone" on workout_sets
  for all
  using (true)
  with check (true); 